version: "3.3"
services:
  nginx:
    build:
      context: ./docker/nginx
    container_name: validol_nginx
    ports:
      - 443:443
    depends_on:
      - superset

  superset:
    build:
      context: ./docker/superset
    container_name: validol_superset
    volumes:
      - superset_home:/app/superset_home

  loader:
    env_file: ./docker/loader/.env
    build:
      context: ./docker/loader
    container_name: validol_loader_cron
    command: sh /app/scripts/init.sh
    volumes:
      - ./docker/loader/scripts:/app/scripts

  db_init:
    env_file: ./docker/db_init/.env
    build:
      context: ./docker/db_init
    container_name: validol_db_init
    command: sh /app/scripts/init.sh
    volumes:
      - ./docker/db_init/scripts:/app/scripts
    depends_on:
      - db

  db:
    env_file: ./docker/db/.env
    image: postgres:12
    container_name: validol_db
    ports:
      - 5432:5432
    volumes:
      - db_home:/var/lib/postgresql/data

volumes:
  db_home:
    external: false
  superset_home:
    external: false
